desktop: fix worker tar extraction for linux
The "data" filter in pythons tarfile library seems to be broken with relative symlink targets.
We tested that the error produced by tar (see below) is indeed a fluke.

Previous error that this fixes:
tarfile.LinkOutsideDestinationError: 'python/share/terminfo/1/1178' would link to '/home/runner/work/transcribee/transcribee/desktop/src-tauri/a/adm1178', which is outside the destination